services:
  - type: web
    name: elite-estates-backend
    runtime: node
    repo: https://github.com/abrehman217788-code/real-estate
    branch: master
    buildCommand: npm run build
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://elite-estates-three.vercel.app
      - key: PORT
        value: 10000
